Using compressed reader for benchmark data
f5/otel-arrow-adapter pull request #174
Opened 2023-06-08 16:58 UTC by moh-osman3

[WIP] not working

2023-06-09 16:29 UTC, lquerel requested changes
First of all, thanks for adding the support for the JSON format. But I'd like to keep the option to generate and read metrics/logs/traces data in a binary format. The main reason is that I have a bunch of data already used in various benchmarks and I need to keep them in order to reproduce them. 

The JSON+ZSTD should be integrated as an additional supported format and not as a replacement for the binary format.

2023-06-09 16:29 UTC, lquerel commented on pkg/benchmark/dataset/real_logs_dataset.go
>  // NewRealLogsDataset creates a new RealLogsDataset from a binary file.
Will be good to adjust the comment as the nature of the input file is no longer a binary proto file. Same comment for the other OTLP entities (metrics and traces).

2023-06-09 16:29 UTC, lquerel commented on tools/logs_benchmark/main.go
> +		} else if strings.HasSuffix(inputFile, ".json") {
I still need to be able to support protobuf files, so the JSON input format should be in addition to the other formats already supported.

2023-06-09 16:29 UTC, lquerel commented on tools/logs_benchmark/main.go
> +		println("\nNo input file specified, using default file ./data/otlp_logs.json")
I'd like to keep the protobuf format the default one (as I'm still using it). The `.json` file extension can be used to detect the format and use the correct reader.

2023-06-09 16:29 UTC, lquerel commented on tools/logs_gen/main.go
> +var outputFile = "./data/otlp_logs.json"
I'd like to keep the ability to generate logs/metrics/traces in binary format (proto). I'm ok to add an option to generate a json version with zstd compression.

2023-06-12 20:32 UTC, moh-osman3 commented on pkg/benchmark/dataset/real_logs_dataset.go
>  // NewRealLogsDataset creates a new RealLogsDataset from a binary file.
Thanks for the review! Updated the comments

2023-06-12 20:32 UTC, moh-osman3 commented on tools/logs_benchmark/main.go
> +		} else if strings.HasSuffix(inputFile, ".json") {
Now supporting both json and the original proto format

2023-06-12 20:32 UTC, moh-osman3 commented on tools/logs_benchmark/main.go
> +		println("\nNo input file specified, using default file ./data/otlp_logs.json")
protobuf is now the default, so all the tools in this repo should work exactly as it was before this change. But now to access the compressed json tooling you must specify a `-format json` option

2023-06-12 20:32 UTC, moh-osman3 commented on tools/logs_gen/main.go
> +var outputFile = "./data/otlp_logs.json"
Fixed!

2023-06-12 20:50 UTC, lquerel commented on tools/logs_benchmark/main.go
> +		} else if strings.HasSuffix(inputFile, ".json") {
Thanks

2023-06-12 20:51 UTC, lquerel approved these changes

2023-06-12 23:12 UTC, moh-osman3 commented
> @moh-osman3 there is an issue in the build process preventing us to merge this PR. Could you fix it and I will merge this PR. Thanks.

@lquerel Ahh forgot to update one of the test files with the updated function signature. I think it should be fixed now. Thank you!

2023-06-12 23:30 UTC, merged

2023-06-12 23:31 UTC, lquerel commented
@moh-osman3 thanks for this PR.